#!/bin/bash

# alp で解析
echo
echo ":: ACCESS LOG       ====>"
sudo cat /var/log/nginx/access.log | alp ltsv --sort sum -r -m "/api/player/competition/.+/ranking,/api/player/player/.+,/api/organizer/player/.+/disqualified, /api/organizer/competition/.+/finish,/api/organizer/competition/.+/score"


# スロークエリを解析
echo
echo ":: SQL LOG       ====>"
sudo mysqldumpslow -s t /var/log/mysql/slow.log | head -n 50

echo
echo ":: QUERY DIGEST  ====>"
sudo pt-query-digest /var/log/mysql/slow.log > /tmp/digest.txt
head -20 /tmp/digest.txt
echo ": see /tmp/digest.txt"

